# Generated by Django 3.2.9 on 2021-12-06 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0006_alter_art_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='likes',
        ),
        migrations.AddField(
            model_name='art',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
