# Generated by Django 3.2.9 on 2021-12-06 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0008_alter_art_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='likes',
        ),
        migrations.AddField(
            model_name='art',
            name='likes',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='likers', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
