# Generated by Django 3.2.9 on 2021-12-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_alter_art_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='likes',
        ),
    ]
