# Generated by Django 3.2.9 on 2021-12-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0013_alter_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
